//----------------------------------------------------------
// Copyright (C) Microsoft Corporation. All rights reserved.
//----------------------------------------------------------
var __extends=this.__extends||function(b,a){for(var c in a)if(a.hasOwnProperty(c))b[c]=a[c];function d(){this.constructor=b}d.prototype=a.prototype;b.prototype=new d};define(["require","exports","Presentation/Scripts/TFS/TFS","Presentation/Scripts/TFS/TFS.Core","Presentation/Scripts/TFS/TFS.Diag","Presentation/Scripts/TFS/TFS.OM","WorkItemTracking/Scripts/TFS.WorkItemTracking","Presentation/Scripts/TFS/Resources/TFS.Resources.Presentation","Presentation/Scripts/TFS/TFS.UI","Presentation/Scripts/TFS/TFS.UI.Controls"],function(u,g,l,e,b,k,d,i,p,j){var c=e.delegate,a=p.domElem;(function(a){a[a.Add=0]="Add";a[a.Delete=1]="Delete"})(g.TagChangeType||(g.TagChangeType={}));var t=g.TagChangeType;function s(a){a.preventDefault();a.stopPropagation();$(this).focus()}function r(a){this._removeTagAndSetFocus(a)}function o(a,c){b.assertParamIsString(a,"name");b.assertParamIsInteger(c,"limit");var d=a;if(a.length>c)d=a.substring(0,c-4)+f.ELLIPSIS;return d}function q(a){b.assertParamIsArray(a,"tagDefinitions");var c=$.map(a,function(a){return a.name});return c}function m(d,g){b.assertParamIsJQueryObject(d,"$offScreenTagsContainer");var c=$(a("li","tag-item tags-overflow")),e=h.generateTagContainer(g);e.children(".tag-box").text(f.ELLIPSIS);e.prependTo(c);c.appendTo(d);return c}var f=function(f){__extends(d,f);function d(a){f.call(this,a)}d.prototype.initializeOptions=function(a){f.prototype.initializeOptions.call(this,$.extend({coreCssClass:d.coreCssClass,tags:[],readOnly:false},a))};d.prototype.initialize=function(){f.prototype.initialize.call(this);var c=this.getElement(),b;this._options.tagLabel&&$(a("span","tags-label")).text(this._options.tagLabel).appendTo($(a("div","tags-label-container")).appendTo(c));this._$tagsList=$(a("ul"));!this._options.readOnly&&this._initializeInputElements();b=$(a("div","tags-items-container"));this._$tagsList.appendTo(b);b.appendTo(c);this._options.tags&&this.setItems(this._options.tags)};d.prototype.addTag=function(c){b.assertParamIsString(c,"name");var a;if(c){a=c.trim();if(a&&!e.ArrayUtils.contains(this._tags,a,e.StringUtils.localeIgnoreCaseComparer)){this._tags.push(a);this._renderItems();this._fireChange({type:0,name:a})}}};d.prototype.removeTag=function(a){this._removeTag(a,true)};d.prototype.setItems=function(a){b.assertParamIsArray(a,"tags");this._tags=a;!this._options.unsorted&&this._tags.sort(this._options.tagSort||e.StringUtils.localeIgnoreCaseComparer);this._renderItems()};d.prototype.clearItems=function(){this.flush();this._tags=[];this._renderItems()};d.prototype.setTagCount=function(a){b.assertParamIsFunction(a,"getTagCount");this._options.getTagCount=a};d.prototype.setMaxWidth=function(a){b.assertParamIsInteger(a,"maxWidth");this._options.maxWidth=a};d.prototype.getWidth=function(){return this._width};d.prototype._splitAndAddTags=function(d){var a,c,b;b=d.split(/,|;/);for(a=0,c=b.length;a<c;a++)this.addTag(b[a])};d.prototype._showInputControl=function(){this._$addButtonContainer.hide();this._$tagInput.val("");!this._$tagInput.data("ui-autocomplete")&&this._$tagInput.autocomplete();this._$tagInput.autocomplete("enable");this._$tagInput.css("display","inline-block");this._$tagInput.focus()};d.prototype._hideInputControl=function(a){this._$tagInput.val("");if(this._$tagInput.is(":visible")){this._$tagInput.css("display","none");this._$tagInput.autocomplete("close");this._$tagInput.autocomplete("disable");this._$addButtonContainer.show()}a&&this._$addButtonContainer.children(0).focus()};d.prototype._renderTagsInContainer=function(c){b.assertParamIsJQueryObject(c,"$container");for(var f,e,a=this._tags.length-1;a>=0;a--){f=this._renderTag(this._tags[a],o(this._tags[a],d.TAG_CHARACTER_LIMIT));f.prependTo(c)}e=c.find(".tag-item").not(".tags-overflow");return e};d.prototype._renderTagsWithMaxWidth=function(d,h,c){b.assertParamIsObject(d,"elements");b.assertParamIsJQueryObject(c,"$overflow");var j=this,e,l,a,f,g=[],i;if(h){a=0;f=0;i=c.width();while(d[a]&&h-f>$(d[a]).outerWidth(true)){f=f+$(d[a]).outerWidth(true);a++}if(a!==d.length)while(d[a-1]&&h-f<i){f=f-$(d[a-1]).outerWidth(true);a--}}for(e=0;e<a;e++)$(d[e]).appendTo(this._$tagsList);for(e=a,l=d.length;e<l;e++)g.push(this._tags[e]);if(g.length>0){if(this._options.type==="grid")c.attr("title",g.join(k.TagService.TAG_FORMATTING_SEPARATOR));else{c.click(function(){j._overflowClick(j,c)});c.keydown(function(a){a.keyCode===13&&c.click()})}c.appendTo(this._$tagsList)}else c.remove()};d.prototype._render=function(){$("li.tag-item",this._$tagsList).remove();this._renderTagsInContainer(this._$tagsList)};d.prototype._renderForGrid=function(){var f,g,e,d,c,b;b=$(this.getElement().parent(".grid-cell")).clone();d=$(a("div","tags-items-container off-screen"));c=$(a("ul","tags-unused-host"));c.appendTo(d);d.appendTo(b);b.appendTo(document.body);e=m(c,false);f=this._renderTagsInContainer(c);g=b.width();this._renderTagsWithMaxWidth(f,g,e);b.remove()};d.prototype._renderFilterAvailable=function(){var f,e,d,b,c;$("li.tag-item",this._$tagsList).remove();c=$(this.getElement().parent(".tfs-tags-filter")).clone();d=$(a("div","tags-items-container off-screen"));b=$(a("ul","tags-unused-host"));b.appendTo(d);d.appendTo(c);c.appendTo(document.body);e=m(b,this._options.selectable).attr("title",i.TagFilterDropdownTooltip);f=this._renderTagsInContainer(b);this._renderTagsWithMaxWidth(f,this._options.maxWidth,e);c.remove()};d.prototype._renderFilterApplied=function(){var r=this,g=this._options.maxTags,n,p,e,j,c,b,q,i,f,l,m=[];$("li.tag-item",this._$tagsList).remove();e=$(this.getElement().parent(".tfs-tags-filter")).clone();j=$(a("div","tags-items-container off-screen"));c=$(a("ul","tags-unused-host"));c.appendTo(j);j.appendTo(e);e.appendTo(document.body);if(!this._tags){this._width=0;return}n=this._tags.length>g?g-1:this._tags.length-1;for(b=n;b>=0;b--){p=this._renderTag(this._tags[b],o(this._tags[b],d.TAG_CHARACTER_LIMIT));p.prependTo(c)}if(this._tags.length>g){l=h.generateTagContainer();l.children(".tag-box").text(d.ELLIPSIS);f=$(a("li","tag-item tags-overflow"));f.append(l);for(b=g,q=this._tags.length;b<q;b++)m.push(this._tags[b]);f.attr("title",m.join(k.TagService.TAG_FORMATTING_SEPARATOR));f.appendTo(c)}i=0;$.map(c.children(),function(a){i=i+$(a).outerWidth(true);r._$tagsList.append(a)});this._width=i;e.remove()};d.prototype._initializeFilterDropdown=function(){var b=this,f=false;function c(){b._$tagInput.hide();b._$tagInput.val("");b._$tagInput.autocomplete("disable");$(".tags-filter-overflow-text").toggleClass("pressed",false)}function d(a){$.inArray(a,b._tags)>=0&&b._options.availableDropdownSelect(a)}this._$tagInput=$(a("input","tags-input tags-filter-dropdown-input tag-box")).attr("type","text").attr("placeholder","").hide();this._$tagInput.autocomplete({delay:0,minLength:0,position:{my:"left top",at:"left bottom",offset:"0 -1"},source:function(d,c){var a=b._getMatchesForPrefix(d.term,b._tags.sort(e.StringUtils.localeIgnoreCaseComparer),true);c(a)},open:function(){f=true},select:function(b,a){d(a.item.value);c()},change:function(){d(b._$tagInput.val());c()},close:function(){f=false;if(!b._$tagInput.is(":focus")){b._$tagInput.val()&&d(b._$tagInput.val());c()}}});this._$tagInput.blur(function(){!f&&c()});this._$tagInput.focus(function(){b._$tagInput.is(":visible")&&b._$tagInput.autocomplete("search")});this._$tagInput.keydown(function(a){if(a.keyCode===27){b._$tagInput.autocomplete("close");c()}else if(a.keyCode===13)if($.inArray(b._$tagInput.val(),b._tags)>=0){b._options.availableDropdownSelect(b._$tagInput.val());b._$tagInput.autocomplete("close");c()}});this._$tagInput.data("ui-autocomplete").menu.element.addClass("tags-autocomplete-menu");this._$tagInput.data("ui-autocomplete")._renderItem=function(e,b){var d=b.label,c;c=$(a("a")).text(d).attr("title",b.value);return $(a("li")).data("ui-autocomplete-item",b).append(c).appendTo(e)};$(window).resize(function(){b._$tagInput.autocomplete("close")});$(document.body).append(this._$tagInput)};d.prototype._overflowClick=function(a,c){b.assertParamIsObject(a,"that");b.assertParamIsJQueryObject(c,"$overflow");c.children().first().addClass("tags-filter-overflow-text");!this._$tagInput&&this._initializeFilterDropdown();a._$tagInput.show();a._$tagInput.autocomplete("enable");$(".tags-filter-overflow-text").toggleClass("pressed",true);a._$tagInput.position({my:"right top",at:"right bottom",of:c.children().first(),offset:"0 0"});a._$tagInput.autocomplete("search");a._$tagInput.focus()};d.prototype._renderItems=function(){this._$tagInput&&this._$tagInput.data("ui-autocomplete")&&this._$tagInput.autocomplete("close");if(!this._options.type)this._render();else if(this._options.type==="grid")this._renderForGrid();else if(this._options.type==="filter.available")this._renderFilterAvailable();else this._options.type==="filter.applied"&&this._renderFilterApplied()};d.prototype._renderTag=function(e,g){var j=this;b.assertParamIsStringNotEmpty(e,"fullTagName");var d,f,k,i;if(!g)g=e;f=$(a("li","tag-item")).attr("title",e);this._options.useDeleteExperience&&f.addClass("tag-item-delete-experience");d=h.generateTagContainer(this._options.selectable,this._options.useDeleteExperience);if(this._options.selectable){d.click(s);d.keydown(function(a){a.KeyCode===13&&d.click()});$.isFunction(this._options.tagClick)&&d.click({tagName:e},this._options.tagClick);d.keydown({tagName:e},$.isFunction(this._options.tagKeyDown)?this._options.tagKeyDown:c(this,r));d.appendTo(f)}if($.isFunction(this._options.tagRenderer))this._options.tagRenderer(d,e,g);else d.children(".tag-box").text(g);d.appendTo(f);if(Boolean(this._options.useDeleteExperience)){i=$("<span>&nbsp;</span>").addClass("tag-delete tag-box tag-box-delete-experience");d.append(i);i.click(function(a){j._removeTagAndSetFocus(a)})}return f};d.prototype._removeTagAndSetFocus=function(b){var a,c,e=b.keyCode===46,g=b.keyCode===8,d=$(b.target).hasClass("tag-delete"),h=p.BrowserCheckUtils.isLessThanOrEqualToIE8();if(e||g||d){b.preventDefault();b.stopPropagation();a=$(b.target).parents(".tag-item");c=e||d?a.next(".tag-item"):a.prev(".tag-item");if(!c[0])c=e||d?a.prev(".tag-item"):a.next(".tag-item");function f(){if(c[0])c.children().focus();else a.next(".tags-add-button").children().focus()}if(d&&!h)a.fadeTo(50,0,function(){a.hide(100,"linear",function(){f();a.remove()})});else{f();a.remove()}this._removeTag(a.attr("title"),false)}};d.prototype._removeTag=function(a,c){b.assertParamIsString(a,"name");if(a&&e.ArrayUtils.contains(this._tags,a,e.StringUtils.localeIgnoreCaseComparer)){this._tags.splice($.inArray(a,this._tags),1);c&&this._renderItems();this._fireChange({type:1,name:a})}};d.prototype._getMatchesForPrefix=function(g,c,h){b.assertParamIsString(g,"prefix");b.assertParamIsArray(c,"items");var a,f=d.AUTOCOMPLETE_MATCHES_LIMIT+1;if(!g)if(c.length<f)a=c;else return[];else{var j=$.ui.autocomplete.escapeRegex(g),i=new RegExp("^"+j,"i");a=$.grep(c||[],function(a){return f>0&&(i.test(a)?f-->0:false)});if(f<=0)return[]}if(!Boolean(h))a=e.ArrayUtils.subtract(a,this._tags,e.StringUtils.localeIgnoreCaseComparer);return a};d.prototype.gettingSuggestedTagNamesForPrefix=function(c){var d=this,a=this._getSuggestedValues().then(function(a){b.logTracePoint("TagControl.getAutoCompleteMatches.start");var e=d._getMatchesForPrefix(c,a,false);b.logTracePoint("TagControl.getAutoCompleteMatches.completed");return e});return a};d.prototype._initializeSuggestedValues=function(){var b=this;this._$tagInput.autocomplete({delay:0,minLength:0,position:{my:"left top",at:"left bottom",collision:"none",offset:"0 -1"},source:function(c,a){b.gettingSuggestedTagNamesForPrefix(c.term).done(function(b){a(b)}).fail(function(){a([])})},select:function(c,a){b.addTag(a.item.value);b._hideInputControl(true)},change:function(){b.flush()},close:function(){if(!b._$tagInput.is(":focus")){b._$tagInput.val()&&b.flush();b._hideInputControl()}}});this._$tagInput.data("ui-autocomplete").menu.element.addClass("tags-autocomplete-menu");this._$tagInput.data("ui-autocomplete")._renderItem=function(e,b){var d=b.label,c;c=$(a("a")).text(d).attr("title",b.value);return $(a("li")).data("ui-autocomplete-item",b).append(c).appendTo(e)}};d.prototype._getSuggestedValues=function(){if(!this._gettingSuggestedValues){var a=jQuery.Deferred();if($.isFunction(this._options.beginGetSuggestedValues))this._options.beginGetSuggestedValues(function(b){var c=q(b);a.resolve(c)});else a.resolve([]);this._gettingSuggestedValues=a.promise()}return this._gettingSuggestedValues};d.prototype.resetSuggestedValues=function(){this._gettingSuggestedValues=null};d.prototype._initializeInputElements=function(){var b=this,c,d;this._$addButtonContainer=$(a("li","tags-add-button"));Boolean(this._options.useDeleteExperience)&&this._$addButtonContainer.addClass("tag-item-delete-experience");c=h.generateTagContainer(true);c.children(".tag-box").text(i.AddButtonText);c.click(function(){b._showInputControl()});c.keydown(function(a){if(a.keyCode===13)c.click();else if(a.keyCode===8){a.preventDefault();a.stopPropagation()}});d=$(a("li"));Boolean(this._options.useDeleteExperience)&&d.addClass("tag-item-delete-experience");this._$tagInput=$(a("input","tags-input tag-box")).attr({type:"text",placeholder:""}).hide();this._$tagInput.change(function(a){a.stopPropagation();a.preventDefault()});$.isFunction(b._options.beginGetSuggestedValues)&&b._initializeSuggestedValues();this._$tagInput.focus(function(){b._$tagInput.autocomplete("search")});this._$tagInput.blur(function(){var a=$(this);if(!a.data("ui-autocomplete").menu.element.is(":visible"))!a.val()&&b._hideInputControl()});this._$tagInput.keydown(function(a){if(a.keyCode===13||a.keyCode===9){b._splitAndAddTags($(this).val());if(a.keyCode===9){b._hideInputControl(true);a.shiftKey&&a.preventDefault()}else{$(this).val("");a.preventDefault();a.stopPropagation();$.isFunction(b._options.beginGetSuggestedValues)&&b._$tagInput.autocomplete("search")}}else if(a.keyCode===27){a.stopPropagation();b._hideInputControl(true)}});c.appendTo(this._$addButtonContainer);this._$addButtonContainer.appendTo(this._$tagsList);this._$tagInput.appendTo(d);d.appendTo(this._$tagsList)};d.prototype.flush=function(){var a;a=this._$tagInput.val();a&&this._splitAndAddTags(a);this._hideInputControl()};d._typeName="tfs.ui.tagcontrol";d.TAG_CHARACTER_LIMIT=30;d.AUTOCOMPLETE_CHARACTER_LIMIT=15;d.AUTOCOMPLETE_MATCHES_LIMIT=200;d.FILTER_DROPDOWN_WIDTH=150;d.ELLIPSIS="...";d.coreCssClass="tfs-tags";return d}(j.BaseControl);g.TagControl=f;l.initClassPrototype(f,{_tags:null,_$tagsList:null,_$tagInput:null,_$addButtonContainer:null,_gettingSuggestedValues:null,_width:null});var n=function(k){__extends(g,k);function g(a){k.call(this,a);this._refreshDelegate=c(this,this._refresh);this._suppressDuplicateRenders=false}g.prototype.initializeOptions=function(a){k.prototype.initializeOptions.call(this,$.extend({coreCssClass:g.coreCssClass},a))};g.prototype.initialize=function(){this._addStaticElements();this._appliedFiltersTagControl=j.BaseControl.createIn(f,this.getElement(),{readOnly:true,selectable:true,cssClass:"tag-filter-applied-tags",tagClick:c(this,this._onAppliedTagClick),tagKeyDown:c(this,this._onAppliedTagKeyDown),unsorted:true,maxTags:g.APPLIED_TAGS_LIMIT,type:"filter.applied"});this._availableFiltersTagControl=j.BaseControl.createIn(f,this.getElement(),{readOnly:true,selectable:true,cssClass:"tag-filter-available-tags",tagClick:c(this,this._onAvailableTagClick),tagKeyDown:c(this,this._onAvailableTagKeyDown),tagSort:c(this,this._tagSortByCount),tagRenderer:c(this,this._renderTagWithCounts),availableDropdownSelect:c(this,this._onAvailableDropdownSelect),type:"filter.available"});this._bindEvents()};g.prototype.bindFilterManager=function(a){b.assertParamIsObject(a,"filterManager");this._filterManager&&this._detachFilterManagerEvents();this._filterManager=a;this._tagFilterProvider=this._filterManager.getFilterProvider(d.TagFilterProvider.PROVIDER_TYPE);this._attachFilterManagerEvents();this._availableFiltersTagControl.setTagCount(c(this,this._tagFilterProvider.getTagItemCount));this._refresh()};g.prototype.bindToData=function(a){b.assertParamIsObject(a,"tagAssociation");this._tagFilterProvider.setTags(a)};g.prototype.clear=function(){this._setInnerTagControls([],[])};g.prototype._bindEvents=function(){var b=this,a=-1;$(window).bind("resize",function(){var c=b.getElement().width();if(a!=c){a=c;b._refresh()}})};g.prototype._getAvailableWidth=function(){var b,a;a=this._appliedFiltersTagControl._width;a=a+this._showAllButton.outerWidth(true);a=a+this._tagsLabel.outerWidth(true);a=a+g.APPLIED_AVAILABLE_SPACER;b=this.getElement().parent().outerWidth(true);return Math.floor(b-a)};g.prototype._addStaticElements=function(){var b,d=this.getElement();this._tagsLabel=$(a("div","tag-filter-control-label")).text(i.TagFilterLabel);d.append(this._tagsLabel);b=$(a("div","tag-filter-control-show-all-container"));this._showAllButton=h.generateTagContainer(true).attr("title",i.TagFilterShowAllButtonTooltip).addClass("tag-filter-control-show-all").click(function(a){a.preventDefault();a.stopPropagation();$(this).focus()}).click(c(this,this._onShowAllClick)).keydown(function(a){a.keyCode===13&&$(this).click()});this._showAllButton.children(".tag-box").text(i.TagFilterShowAllButtonText);b.append(this._showAllButton);d.append(b)};g.prototype._attachFilterManagerEvents=function(){this._filterManager.attachEvent(d.FilterManager.EVENT_FILTER_CHANGED,this._refreshDelegate);this._filterManager.attachEvent(d.FilterManager.EVENT_FILTER_CLEARED,this._refreshDelegate);this._filterManager.attachEvent(d.FilterManager.EVENT_WORK_ITEM_UPDATED,this._refreshDelegate)};g.prototype._detachFilterManagerEvents=function(){this._filterManager.detachEvent(d.FilterManager.EVENT_FILTER_CHANGED,this._refreshDelegate);this._filterManager.detachEvent(d.FilterManager.EVENT_FILTER_CLEARED,this._refreshDelegate);this._filterManager.detachEvent(d.FilterManager.EVENT_WORK_ITEM_UPDATED,this._refreshDelegate)};g.prototype._refresh=function(){this._tagFilterProvider.isActive()&&this._setInnerTagControls(this._tagFilterProvider.getActiveFilterTags(),this._tagFilterProvider.getAvailableFilterTags())};g.prototype._setInnerTagControls=function(c,a){if(!this._suppressDuplicateRenders){this._suppressDuplicateRenders=true;this._appliedFiltersTagControl.setItems(c);this._availableFiltersTagControl.setMaxWidth(this._getAvailableWidth());this._availableFiltersTagControl.setItems(a);this._suppressDuplicateRenders=false;b.logTracePoint("TagFilterControl.renderComplete")}};g.prototype._onAvailableDropdownSelect=function(a){this._filterManager.addFilter(d.TagFilterProvider.PROVIDER_TYPE,a)};g.prototype._onAvailableTagClick=function(c){var a=c.data.tagName;b.logTracePoint("TagFilterControl.AvailableTag.Clicked");this._filterManager.addFilter(d.TagFilterProvider.PROVIDER_TYPE,a)};g.prototype._onAvailableTagKeyDown=function(b){var a=false;this._commonTagKeyDownBehavior(a,b)};g.prototype._onAppliedTagClick=function(c){var a=c.data.tagName;b.logTracePoint("TagFilterControl.AppliedTag.Clicked");this._filterManager.removeFilter(d.TagFilterProvider.PROVIDER_TYPE,a)};g.prototype._onAppliedTagKeyDown=function(b){var a=true;this._commonTagKeyDownBehavior(a,b)};g.prototype._commonTagKeyDownBehavior=function(c,a){var b;if(a.keyCode===13){a.preventDefault();a.stopPropagation();if(c)this._onAppliedTagClick(a);else this._onAvailableTagClick(a);if(c)b=this._appliedFiltersTagControl.getElement().find(".tag-item .tag-container").last();else b=this._availableFiltersTagControl.getElement().find(".tag-item .tag-container").first();if(b.length===0)b=this._showAllButton;b.focus()}};g.prototype._onShowAllClick=function(){this._filterManager&&this._filterManager.clearFilters(d.TagFilterProvider.PROVIDER_TYPE)};g.prototype._renderTagWithCounts=function(c,e,d){var b;c.children(".tag-box").text(d);b=$(a("span","tag-item-count")).text(this._tagFilterProvider.getTagItemCount(e).toString());c.children(".tag-box").append(b)};g.prototype._tagSortByCount=function(b,c){var a,d=this._tagFilterProvider.getTagItemCount(b),f=this._tagFilterProvider.getTagItemCount(c);a=f-d;return a?a:e.StringUtils.localeIgnoreCaseComparer(b,c)};g._typeName="tfs.ui.tagfiltercontrol";g.coreCssClass="tfs-tags-filter";g.APPLIED_TAGS_LIMIT=5;g.APPLIED_AVAILABLE_SPACER=100;return g}(j.BaseControl);g.TagFilterControl=n;l.initClassPrototype(n,{_tagsLabel:null,_filterManager:null,_tagFilterProvider:null,_availableFiltersTagControl:null,_appliedFiltersTagControl:null,_showAllButton:null,_refreshDelegate:null});var h=function(){function c(){}c.renderTagCellContents=function(m,l,d,i){b.assertParamIsObject(d,"column");var c,g,h,e;g=d.getColumnValue.call(m,l,d.index,i);c=g?g.split(k.TagService.TAG_SPLITTING_SEPARATOR):[];$.each(c,function(b,a){c[b]=$.trim(a)});e=$(a("div","grid-cell"));e.width(d.width||20);if(c&&c.length>0){j.BaseControl.createIn(f,e,{tags:c,readOnly:true,type:"grid"});h=c.join("     ");d.maxLength=Math.max(d.maxLength||0,h.length)}else e.html("&nbsp;");return e};c.generateTagContainer=function(e,d){var b=$(a("span","tag-container")),c=$(a("span","tag-box"));if(e){b.attr("tabindex",0);if(d){c.addClass("tag-box-delete-experience");b.addClass("tag-container-delete-experience")}else{b.addClass("tag-container-selectable");c.addClass("tag-box-selectable")}}c.attr("dir","ltr");b.attr("dir","ltr");b.append(c);return b};c._typeName="tfs.ui.tagutilities";return c}();g.TagUtilities=h;l.tfsModuleLoaded("TFS.UI.Tags",g)});
// SIG // Begin signature block
// SIG // MIIaoQYJKoZIhvcNAQcCoIIakjCCGo4CAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFIo5fJw3DnYJ
// SIG // Je6Z42SOX0KUBoKkoIIVejCCBLswggOjoAMCAQICEzMA
// SIG // AABZ1nPNUY7wIsUAAAAAAFkwDQYJKoZIhvcNAQEFBQAw
// SIG // dzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBMB4XDTE0MDUyMzE3
// SIG // MTMxNVoXDTE1MDgyMzE3MTMxNVowgasxCzAJBgNVBAYT
// SIG // AlVTMQswCQYDVQQIEwJXQTEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MQ0wCwYDVQQLEwRNT1BSMScwJQYDVQQLEx5uQ2lwaGVy
// SIG // IERTRSBFU046RjUyOC0zNzc3LThBNzYxJTAjBgNVBAMT
// SIG // HE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggEi
// SIG // MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDGbE7P
// SIG // aFP974De6IvEsfB+B84ePOwMjDWHTOlROry2sJZ3Qvr/
// SIG // PM/h2uKJ+m5CAJlbFt0JZDjiUvvfjvqToz27h49uuIfJ
// SIG // 0GBPz5yCkW2RG3IQs9hDfFlKYF3GsFXQJ9vy9r3yIMYi
// SIG // LJ5riy1s6ngEyUvBcAnnth2vmowGP3hw+nbu0iQUdrKu
// SIG // ICiDHKnwSJI/ooX3g8rFUdCVIAN50le8E7VOuLRsVh9T
// SIG // HhW7zzA//TsBzV9yaPfK85lmM6hdIo8dbsraZdIrHCSs
// SIG // n3ypEIqF4m0uXEr9Sbl7QLFTxt9HubMjTiJHHNPBuUl2
// SIG // QnLOkIYOJPXCPLkJNj+oU1xW/l9hAgMBAAGjggEJMIIB
// SIG // BTAdBgNVHQ4EFgQUWygas811DWM9/Zn1mxUCSBrLpqww
// SIG // HwYDVR0jBBgwFoAUIzT42VJGcArtQPt2+7MrsMM1sw8w
// SIG // VAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL2NybC5taWNy
// SIG // b3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljcm9z
// SIG // b2Z0VGltZVN0YW1wUENBLmNybDBYBggrBgEFBQcBAQRM
// SIG // MEowSAYIKwYBBQUHMAKGPGh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljcm9zb2Z0VGltZVN0
// SIG // YW1wUENBLmNydDATBgNVHSUEDDAKBggrBgEFBQcDCDAN
// SIG // BgkqhkiG9w0BAQUFAAOCAQEAevAN9EVsNJYOd/DiwEIF
// SIG // YfeI03r9iNWn9fd/8gj21f3LynR82wmp39YVB5m/0D6H
// SIG // hGJ7wgaOyoto4j3fnlrFjLKpXP5ZYib11/l4tm60CpBl
// SIG // ZulRCPF8yaO3BDdGxeeCPihc709xpOexJVrlQ1QzCH+k
// SIG // sFUt0YJwSBEgDSaBDu8GJXSrhcPDjOIUX+gFVI+6homq
// SIG // lq6UYiX5r2mICgyxUcQJ77iAfFOQebvpj9BI8GLImfFl
// SIG // NDv3zrX7Zpi5olmZXT6VnxS/NbT7mHIkKQzzugR6gjn7
// SIG // Rs3x4LIWvH0g+Jw5FSWhJi3Wi4G9xr2wnVT+RwtfLU4q
// SIG // 9IfqtQ+1t+2SKTCCBOwwggPUoAMCAQICEzMAAADKbNUy
// SIG // EjXE4VUAAQAAAMowDQYJKoZIhvcNAQEFBQAweTELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEjMCEGA1UEAxMaTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EwHhcNMTQwNDIyMTczOTAw
// SIG // WhcNMTUwNzIyMTczOTAwWjCBgzELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjENMAsGA1UECxMETU9QUjEeMBwGA1UEAxMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMIIBIjANBgkqhkiG9w0B
// SIG // AQEFAAOCAQ8AMIIBCgKCAQEAlnFd7QZG+oTLnVu3Rsew
// SIG // 4bQROQOtsRVzYJzrp7ZuGjw//2XjNPGmpSFeVplsWOSS
// SIG // oQpcwtPcUi8MZZogYUBTMZxsjyF9uvn+E1BSYJU6W7lY
// SIG // pXRhQamU4K0mTkyhl3BJJ158Z8pPHnGERrwdS7biD8XG
// SIG // J8kH5noKpRcAGUxwRTgtgbRQqsVn0fp5vMXMoXKb9CU0
// SIG // mPhU3xI5OBIvpGulmn7HYtHcz+09NPi53zUwuux5Mqnh
// SIG // qaxVTUx/TFbDEwt28Qf5zEes+4jVUqUeKPo9Lc/PhJiG
// SIG // cWURz4XJCUSG4W/nsfysQESlqYsjP4JJndWWWVATWRhz
// SIG // /0MMrSvUfzBAZwIDAQABo4IBYDCCAVwwEwYDVR0lBAww
// SIG // CgYIKwYBBQUHAwMwHQYDVR0OBBYEFB9e4l1QjVaGvko8
// SIG // zwTop4e1y7+DMFEGA1UdEQRKMEikRjBEMQ0wCwYDVQQL
// SIG // EwRNT1BSMTMwMQYDVQQFEyozMTU5NStiNDIxOGYxMy02
// SIG // ZmNhLTQ5MGYtOWM0Ny0zZmM1NTdkZmM0NDAwHwYDVR0j
// SIG // BBgwFoAUyxHoytK0FlgByTcuMxYWuUyaCh8wVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljQ29kU2lnUENB
// SIG // XzA4LTMxLTIwMTAuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNDb2RTaWdQQ0FfMDgtMzEt
// SIG // MjAxMC5jcnQwDQYJKoZIhvcNAQEFBQADggEBAHdc69eR
// SIG // Pc29e4PZhamwQ51zfBfJD+0228e1LBte+1QFOoNxQIEJ
// SIG // ordxJl7WfbZsO8mqX10DGCodJ34H6cVlH7XPDbdUxyg4
// SIG // Wojne8EZtlYyuuLMy5Pbr24PXUT11LDvG9VOwa8O7yCb
// SIG // 8uH+J13oxf9h9hnSKAoind/NcIKeGHLYI8x6LEPu/+rA
// SIG // 4OYdqp6XMwBSbwe404hs3qQGNafCU4ZlEXcJjzVZudiG
// SIG // qAD++DF9LPSMBZ3AwdV3cmzpTVkmg/HCsohXkzUAfFAr
// SIG // vFn8/hwpOILT3lKXRSkYTpZbnbpfG6PxJ1DqB5XobTQN
// SIG // OFfcNyg1lTo4nNTtaoVdDiIRXnswggW8MIIDpKADAgEC
// SIG // AgphMyYaAAAAAAAxMA0GCSqGSIb3DQEBBQUAMF8xEzAR
// SIG // BgoJkiaJk/IsZAEZFgNjb20xGTAXBgoJkiaJk/IsZAEZ
// SIG // FgltaWNyb3NvZnQxLTArBgNVBAMTJE1pY3Jvc29mdCBS
// SIG // b290IENlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0xMDA4
// SIG // MzEyMjE5MzJaFw0yMDA4MzEyMjI5MzJaMHkxCzAJBgNV
// SIG // BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYD
// SIG // VQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
// SIG // Q29ycG9yYXRpb24xIzAhBgNVBAMTGk1pY3Jvc29mdCBD
// SIG // b2RlIFNpZ25pbmcgUENBMIIBIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAQ8AMIIBCgKCAQEAsnJZXBkwZL8dmmAgIEKZdlNs
// SIG // PhvWb8zL8epr/pcWEODfOnSDGrcvoDLs/97CQk4j1XIA
// SIG // 2zVXConKriBJ9PBorE1LjaW9eUtxm0cH2v0l3511iM+q
// SIG // c0R/14Hb873yNqTJXEXcr6094CholxqnpXJzVvEXlOT9
// SIG // NZRyoNZ2Xx53RYOFOBbQc1sFumdSjaWyaS/aGQv+knQp
// SIG // 4nYvVN0UMFn40o1i/cvJX0YxULknE+RAMM9yKRAoIsc3
// SIG // Tj2gMj2QzaE4BoVcTlaCKCoFMrdL109j59ItYvFFPees
// SIG // CAD2RqGe0VuMJlPoeqpK8kbPNzw4nrR3XKUXno3LEY9W
// SIG // PMGsCV8D0wIDAQABo4IBXjCCAVowDwYDVR0TAQH/BAUw
// SIG // AwEB/zAdBgNVHQ4EFgQUyxHoytK0FlgByTcuMxYWuUya
// SIG // Ch8wCwYDVR0PBAQDAgGGMBIGCSsGAQQBgjcVAQQFAgMB
// SIG // AAEwIwYJKwYBBAGCNxUCBBYEFP3RMU7TJoqV4ZhgO6gx
// SIG // b6Y8vNgtMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBB
// SIG // MB8GA1UdIwQYMBaAFA6sgmBAVieX5SUT/CrhClOVWeSk
// SIG // MFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwubWlj
// SIG // cm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL21pY3Jv
// SIG // c29mdHJvb3RjZXJ0LmNybDBUBggrBgEFBQcBAQRIMEYw
// SIG // RAYIKwYBBQUHMAKGOGh0dHA6Ly93d3cubWljcm9zb2Z0
// SIG // LmNvbS9wa2kvY2VydHMvTWljcm9zb2Z0Um9vdENlcnQu
// SIG // Y3J0MA0GCSqGSIb3DQEBBQUAA4ICAQBZOT5/Jkav629A
// SIG // sTK1ausOL26oSffrX3XtTDst10OtC/7L6S0xoyPMfFCY
// SIG // gCFdrD0vTLqiqFac43C7uLT4ebVJcvc+6kF/yuEMF2nL
// SIG // pZwgLfoLUMRWzS3jStK8cOeoDaIDpVbguIpLV/KVQpzx
// SIG // 8+/u44YfNDy4VprwUyOFKqSCHJPilAcd8uJO+IyhyugT
// SIG // pZFOyBvSj3KVKnFtmxr4HPBT1mfMIv9cHc2ijL0nsnlj
// SIG // VkSiUc356aNYVt2bAkVEL1/02q7UgjJu/KSVE+Traeep
// SIG // oiy+yCsQDmWOmdv1ovoSJgllOJTxeh9Ku9HhVujQeJYY
// SIG // XMk1Fl/dkx1Jji2+rTREHO4QFRoAXd01WyHOmMcJ7oUO
// SIG // jE9tDhNOPXwpSJxy0fNsysHscKNXkld9lI2gG0gDWvfP
// SIG // o2cKdKU27S0vF8jmcjcS9G+xPGeC+VKyjTMWZR4Oit0Q
// SIG // 3mT0b85G1NMX6XnEBLTT+yzfH4qerAr7EydAreT54al/
// SIG // RrsHYEdlYEBOsELsTu2zdnnYCjQJbRyAMR/iDlTd5aH7
// SIG // 5UcQrWSY/1AWLny/BSF64pVBJ2nDk4+VyY3YmyGuDVyc
// SIG // 8KKuhmiDDGotu3ZrAB2WrfIWe/YWgyS5iM9qqEcxL5rc
// SIG // 43E91wB+YkfRzojJuBj6DnKNwaM9rwJAav9pm5biEKgQ
// SIG // tDdQCNbDPTCCBgcwggPvoAMCAQICCmEWaDQAAAAAABww
// SIG // DQYJKoZIhvcNAQEFBQAwXzETMBEGCgmSJomT8ixkARkW
// SIG // A2NvbTEZMBcGCgmSJomT8ixkARkWCW1pY3Jvc29mdDEt
// SIG // MCsGA1UEAxMkTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
// SIG // dGUgQXV0aG9yaXR5MB4XDTA3MDQwMzEyNTMwOVoXDTIx
// SIG // MDQwMzEzMDMwOVowdzELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEh
// SIG // MB8GA1UEAxMYTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // n6Fssd/bSJIqfGsuGeG94uPFmVEjUK3O3RhOJA/u0afR
// SIG // TK10MCAR6wfVVJUVSZQbQpKumFwwJtoAa+h7veyJBw/3
// SIG // DgSY8InMH8szJIed8vRnHCz8e+eIHernTqOhwSNTyo36
// SIG // Rc8J0F6v0LBCBKL5pmyTZ9co3EZTsIbQ5ShGLieshk9V
// SIG // UgzkAyz7apCQMG6H81kwnfp+1pez6CGXfvjSE/MIt1Nt
// SIG // UrRFkJ9IAEpHZhEnKWaol+TTBoFKovmEpxFHFAmCn4Tt
// SIG // VXj+AZodUAiFABAwRu233iNGu8QtVJ+vHnhBMXfMm987
// SIG // g5OhYQK1HQ2x/PebsgHOIktU//kFw8IgCwIDAQABo4IB
// SIG // qzCCAacwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU
// SIG // IzT42VJGcArtQPt2+7MrsMM1sw8wCwYDVR0PBAQDAgGG
// SIG // MBAGCSsGAQQBgjcVAQQDAgEAMIGYBgNVHSMEgZAwgY2A
// SIG // FA6sgmBAVieX5SUT/CrhClOVWeSkoWOkYTBfMRMwEQYK
// SIG // CZImiZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJ
// SIG // bWljcm9zb2Z0MS0wKwYDVQQDEyRNaWNyb3NvZnQgUm9v
// SIG // dCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHmCEHmtFqFKoKWt
// SIG // THNY9AcTLmUwUAYDVR0fBEkwRzBFoEOgQYY/aHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvbWljcm9zb2Z0cm9vdGNlcnQuY3JsMFQGCCsGAQUF
// SIG // BwEBBEgwRjBEBggrBgEFBQcwAoY4aHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3NvZnRS
// SIG // b290Q2VydC5jcnQwEwYDVR0lBAwwCgYIKwYBBQUHAwgw
// SIG // DQYJKoZIhvcNAQEFBQADggIBABCXisNcA0Q23em0rXfb
// SIG // znlRTQGxLnRxW20ME6vOvnuPuC7UEqKMbWK4VwLLTiAT
// SIG // UJndekDiV7uvWJoc4R0Bhqy7ePKL0Ow7Ae7ivo8KBciN
// SIG // SOLwUxXdT6uS5OeNatWAweaU8gYvhQPpkSokInD79vzk
// SIG // eJkuDfcH4nC8GE6djmsKcpW4oTmcZy3FUQ7qYlw/FpiL
// SIG // ID/iBxoy+cwxSnYxPStyC8jqcD3/hQoT38IKYY7w17gX
// SIG // 606Lf8U1K16jv+u8fQtCe9RTciHuMMq7eGVcWwEXChQO
// SIG // 0toUmPU8uWZYsy0v5/mFhsxRVuidcJRsrDlM1PZ5v6oY
// SIG // emIp76KbKTQGdxpiyT0ebR+C8AvHLLvPQ7Pl+ex9teOk
// SIG // qHQ1uE7FcSMSJnYLPFKMcVpGQxS8s7OwTWfIn0L/gHkh
// SIG // gJ4VMGboQhJeGsieIiHQQ+kr6bv0SMws1NgygEwmKkgk
// SIG // X1rqVu+m3pmdyjpvvYEndAYR7nYhv5uCwSdUtrFqPYmh
// SIG // dmG0bqETpr+qR/ASb/2KMmyy/t9RyIwjyWa9nR2HEmQC
// SIG // PS2vWY+45CHltbDKY7R4VAXUQS5QrJSwpXirs6CWdRrZ
// SIG // kocTdSIvMqgIbqBbjCW/oO+EyiHW6x5PyZruSeD3AWVv
// SIG // iQt9yGnI5m7qp5fOMSn/DsVbXNhNG6HY+i+ePy5VFmvJ
// SIG // E6P9MYIEkzCCBI8CAQEwgZAweTELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEjMCEGA1UEAxMaTWljcm9zb2Z0IENvZGUgU2ln
// SIG // bmluZyBQQ0ECEzMAAADKbNUyEjXE4VUAAQAAAMowCQYF
// SIG // Kw4DAhoFAKCBrDAZBgkqhkiG9w0BCQMxDAYKKwYBBAGC
// SIG // NwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIB
// SIG // FTAjBgkqhkiG9w0BCQQxFgQUY7sByEw0FMZhhCP8D/u3
// SIG // X94KJ7QwTAYKKwYBBAGCNwIBDDE+MDygIoAgAFQARgBT
// SIG // AC4AVQBJAC4AVABhAGcAcwBfADIALgBqAHOhFoAUaHR0
// SIG // cDovL21pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEBBQAE
// SIG // ggEAK/t6YZ4ltxvwB/3NDSeK7Ac4iQxL8yEnyZy/UwGp
// SIG // /IUgDgX33MSnRpx9grELFzB+k8WISRmwJSmZJqwOdOXg
// SIG // ErrSZNW2di6V6gUDcnt4mp6xVHQcK3F9uLBP7hRQOYMh
// SIG // Gss/17hxF+ViQIbqeG0qmmviTVCu/bBq9/byiG9k5TkQ
// SIG // TY2QdiV7giFpz//5HFnlGNROYHikwvrd8EcsST6bKPPs
// SIG // GL1nu0kfUFnZ+cIlCQHpflhHzyM360UolDOFf8d+d0io
// SIG // rFYRKPFnbVxlahl6FYSJfk9L9lIIclVzK8XrxPLeML3Q
// SIG // 3pfL4C0HqTdZbi9W28md+IdsUqPHzORBgZhALqGCAigw
// SIG // ggIkBgkqhkiG9w0BCQYxggIVMIICEQIBATCBjjB3MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSEwHwYDVQQDExhNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0ECEzMAAABZ1nPNUY7wIsUA
// SIG // AAAAAFkwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzEL
// SIG // BgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE0MDcy
// SIG // MzA5MTAxOVowIwYJKoZIhvcNAQkEMRYEFHDXms0CxOfA
// SIG // 4F9LkplQCZJQDtIsMA0GCSqGSIb3DQEBBQUABIIBABQI
// SIG // opplco5ax6MHZXIaGH1dwUbF9ZpGweoB9f4RaBgID8Ji
// SIG // 37X+FExBvGxpIiJpLa9FF8bHe98k/Scvc8xLGovSZ/zM
// SIG // CUCd73ppYcOmQ6g0SwKYOENi2TRAzuK3r4rNZXIbQUph
// SIG // o1e7wpMZNnIr/0aKk2wNm2E/7MQrJhwvqyQ27ExSrsFf
// SIG // Td0ywbXmW+k2FOIHFFiBW2t5h223RYrchd2MI6Gg9VUW
// SIG // vXZj+Zhzp2QOEkYnfH0nVvQbpKn3NPSQxDnZlFeitTPv
// SIG // +unVcMhBIGYXKwGTBrk5duXaHWFigCEGYWJwmCU0UYWe
// SIG // RvOpFFY94OMzrIymTSMz6aWtlRy09Sg=
// SIG // End signature block
