define(["require", "exports"], function(require, exports) {exports.WiqlOperators_NotEver="Was Never";
exports.WiqlOperators_And="And";
exports.WiqlOperators_Any="[Any]";
exports.WiqlOperators_NotEqualTo="\u003c\u003e";
exports.WiqlOperators_NotUnder="Not Under";
exports.WiqlOperators_Contains="Contains";
exports.WiqlOperators_LessThan="\u003c";
exports.WiqlOperators_MacroProject="Project";
exports.WiqlOperators_Or="Or";
exports.WiqlOperators_In="In";
exports.WiqlOperators_InGroup="In Group";
exports.WiqlOperators_LessThanOrEqualTo="\u003c=";
exports.WiqlOperators_MacroToday="Today";
exports.WiqlOperators_Ever="Was Ever";
exports.WiqlOperators_GreaterThanOrEqualTo="\u003e=";
exports.WiqlOperators_MacroMe="Me";
exports.WiqlOperators_ContainsWords="Contains Words";
exports.WiqlOperators_FieldComparisonQualifier=" [Field]";
exports.WiqlOperators_NotContainsWords="Does Not Contain Words";
exports.WiqlOperators_Under="Under";
exports.WiqlOperators_NotContains="Does Not Contain";
exports.WiqlOperators_MacroTodayMinusDaysFormat="{0} - {1}";
exports.WiqlOperators_GreaterThan="\u003e";
exports.WiqlOperators_EqualTo="=";
exports.WiqlOperators_NotInGroup="Not In Group";
});